### ISSUE TITLE
Appropriately converting the mod into the .pac file.

### ISSUE THREAD

**Issue by JCThornton90** [blueskythlikesclouds/SkythTools#9]
Hello, it's me again!
Firstly, thank you for the support and the helpful tools.

I've completed my custom mod and used the HedgeArcEditor from SFTools to convert the mod into the .PAC files to make it compatible for Sonic Lost World, but something felt odd about the PAC files. Which the Pac.00 file has around 8MB, and the main .Pac file has 7kb. I tested out the mod, and the second I got into the game, it crashed. I've also attempted to include the original Sonic files from the same Pac file directory, but when I attempted to convert the folder into the. Pac file it wouldn't do so unless if there are less files for some reason. So I might have done something wrong or used the wrong tools to convert the mods into the.PAC files.
Is there a more appropriate way to convert the mods into the .PAC files without risking crashing the game? 
Thank you once again, let me know ASAP. :)

**Comment by blueskythlikesclouds** [comment]
Are you sure you are packing with the correct tool? Pack using [HedgeArcPack](https://ci.appveyor.com/project/Radfordhound/hedgelib/builds/45348291/job/igg126jsimr07s83/artifacts) in Sonic Lost World mode. Alternatively, you could also try out [pacpack](https://github.com/DarioSamo/libgens-sonicglvl/blob/master/bin/pacpack.exe).

Also, I'm sorry if this sounds rude, but I'd rather prefer that you only report issues you have with the tools included in this repository instead of asking for general modding support. This is not the place for it.
